//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E2B_Online_Dictionary
{
    using System;
    using System.Collections.Generic;
    
    public partial class word
    {
        public int C_id { get; set; }
        public string en_word { get; set; }
        public string bn_word { get; set; }
        public string status { get; set; }
        public string user_created { get; set; }
        public string TRIAL254 { get; set; }
    }
}
